CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(120) NOT NULL,
                          email VARCHAR(180) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          role VARCHAR(30) NOT NULL,
                          company_start_date DATE NOT NULL,
                          active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title VARCHAR(150) NOT NULL,
                     description TEXT NOT NULL,
                     requirements TEXT NOT NULL,
                     min_company_time INTEGER NOT NULL DEFAULT 0,
                     status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
                     created_by BIGINT NOT NULL REFERENCES app_user(id),
                     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE application (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             candidate_id BIGINT NOT NULL REFERENCES app_user(id),
                             job_id BIGINT NOT NULL REFERENCES job(id) ON DELETE CASCADE,
                             status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
                             feedback TEXT,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT uk_application_candidate_job UNIQUE (candidate_id, job_id)
);

CREATE TABLE notification (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              recipient_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
                              title VARCHAR(180) NOT NULL,
                              message TEXT NOT NULL,
                              read_at TIMESTAMP,
                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_job_status ON job(status);
CREATE INDEX idx_application_candidate ON application(candidate_id);
CREATE INDEX idx_application_job ON application(job_id);
CREATE INDEX idx_notification_recipient ON notification(recipient_id, created_at DESC);