CREATE TABLE tb_user (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(120) NOT NULL,
                         email VARCHAR(180) NOT NULL UNIQUE,
                         password VARCHAR(255) NOT NULL,
                         role VARCHAR(30) NOT NULL,
                         hire_date DATE NOT NULL,
                         active BOOLEAN NOT NULL DEFAULT TRUE,
                         created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE tb_job (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(120) NOT NULL,
                        description TEXT NOT NULL,
                        requirements TEXT NOT NULL,
                        min_company_time INTEGER NOT NULL DEFAULT 0,
                        status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
                        created_by BIGINT NOT NULL REFERENCES tb_user(id),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_application (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                candidate_id BIGINT NOT NULL REFERENCES tb_user(id),
                                job_id BIGINT NOT NULL REFERENCES tb_job(id) ON DELETE CASCADE,
                                status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
                                feedback TEXT,
                                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT uk_application_candidate_job UNIQUE (candidate_id, job_id)
);

CREATE TABLE tb_notification (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 recipient_id BIGINT NOT NULL REFERENCES tb_user(id) ON DELETE CASCADE,
                                 title VARCHAR(180) NOT NULL,
                                 message TEXT NOT NULL,
                                 read_at TIMESTAMP,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_job_status ON tb_job(status);
CREATE INDEX idx_application_candidate ON tb_application(candidate_id);
CREATE INDEX idx_application_job ON tb_application(job_id);
CREATE INDEX idx_notification_recipient ON tb_notification(recipient_id, created_at DESC);